In [7]:
import numpy as np
import pandas as pd

In [9]:
data = np.load('time.npy', encoding='bytes')

In [10]:
pd.Series(data)

0        2015-01-05 10:00:00
1        2015-01-05 10:01:00
2        2015-01-05 10:02:00
3        2015-01-05 10:03:00
4        2015-01-05 10:04:00
5        2015-01-05 10:05:00
6        2015-01-05 10:06:00
7        2015-01-05 10:07:00
8        2015-01-05 10:08:00
9        2015-01-05 10:09:00
10       2015-01-05 10:10:00
11       2015-01-05 10:11:00
12       2015-01-05 10:12:00
13       2015-01-05 10:13:00
14       2015-01-05 10:14:00
15       2015-01-05 10:15:00
16       2015-01-05 10:16:00
17       2015-01-05 10:17:00
18       2015-01-05 10:18:00
19       2015-01-05 10:19:00
20       2015-01-05 10:20:00
21       2015-01-05 10:21:00
22       2015-01-05 10:22:00
23       2015-01-05 10:23:00
24       2015-01-05 10:24:00
25       2015-01-05 10:25:00
26       2015-01-05 10:26:00
27       2015-01-05 10:27:00
28       2015-01-05 10:28:00
29       2015-01-05 10:29:00
                 ...
216293   2016-08-31 18:06:00
216294   2016-08-31 18:07:00
216295   2016-08-31 18:08:00
216296   2016-08-31 18:09:00
216297   2016-08-31 18:10:00
216298   2016-08-31 18:11:00
216299   2016-08-31 18:12:00
216300   2016-08-31 18:13:00
216301   2016-08-31 18:14:00
216302   2016-08-31 18:15:00
216303   2016-08-31 18:16:00
216304   2016-08-31 18:17:00
216305   2016-08-31 18:18:00
216306   2016-08-31 18:19:00
216307   2016-08-31 18:20:00
216308   2016-08-31 18:21:00
216309   2016-08-31 18:22:00
216310   2016-08-31 18:23:00
216311   2016-08-31 18:24:00
216312   2016-08-31 18:25:00
216313   2016-08-31 18:26:00
216314   2016-08-31 18:27:00
216315   2016-08-31 18:28:00
216316   2016-08-31 18:29:00
216317   2016-08-31 18:30:00
216318   2016-08-31 18:31:00
216319   2016-08-31 18:32:00
216320   2016-08-31 18:33:00
216321   2016-08-31 18:34:00
216322   2016-08-31 18:35:00
dtype: datetime64[ns]